# Generated by Django 4.2.30 on 2026-09-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProductPackingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_name', models.CharField(max_length=100)),
                ('packing_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_qty_unit', models.CharField(max_length=50)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_sizes', to='core.product')),
            ],
            options={
                'ordering': ['product', 'packing_value'],
            },
        ),
        migrations.AddConstraint(
            model_name='productpackingsize',
            constraint=models.UniqueConstraint(fields=('product', 'packing_name'), name='unique_product_packing_name'),
        ),
    ]
