# Generated by Django 4.2.30 on 2026-09-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unit_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackingsize',
            name='packing_unit',
            field=models.CharField(choices=[('ml', 'ml'), ('litre', 'Litre')], default='litre', max_length=10),
        ),
        migrations.AlterField(
            model_name='productpackingsize',
            name='base_qty_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
