# Generated by Django 4.2.30 on 2026-09-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_expensehead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packing_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margins', to='core.productpackingsize')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margins', to='core.product')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='productmargin',
            constraint=models.UniqueConstraint(fields=('product', 'packing_size', 'effective_date'), name='unique_product_packing_margin_date'),
        ),
    ]
