# Generated by Django 4.2.30 on 2026-09-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productmargin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='productpackingsize',
            name='packing_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_sizes', to='core.packingunit'),
        ),
    ]
