# Generated by Django 4.2.30 on 2026-09-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_expensehead_vehicle_alter_expense_expense_head'),
        ('core', '0008_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseHead',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
