# Generated by Django 4.0 on 2026-10-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_expensehead_delete_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
