# Generated by Django 4.2.30 on 2026-09-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_expensehead_vehicle_alter_expense_expense_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(
                max_digits=18,
                decimal_places=6
            ),
        ),
    ]